export const MARKALAR = [
  "Toyota",
  "Renault",
  "Fiat",
  "Ford",
  "Volkswagen",
  "Opel",
  "Peugeot",
  "Citroën",
  "Hyundai",
  "Kia",
  "Mercedes-Benz",
  "BMW",
  "Audi",
  "Skoda",
  "Seat",
  "Dacia",
  "Honda",
  "Nissan",
  "Mazda",
  "Mitsubishi",
  "Suzuki",
  "Chevrolet",
  "Volvo",
  "Land Rover",
  "Jeep",
  "Isuzu",
  "Iveco",
  "MAN",
  "Scania",
  "DAF",
  "Tofaş",
  "Diğer",
] as const;

export const MARKA_MODELLERI: Record<string, string[]> = {
  Toyota: ["Corolla", "Yaris", "Auris", "Camry", "C-HR", "RAV4", "Hilux", "Land Cruiser", "Avensis", "Proace"],
  Renault: ["Clio", "Megane", "Symbol", "Fluence", "Talisman", "Captur", "Kadjar", "Kangoo", "Master", "Trafic"],
  Fiat: ["Egea", "Linea", "Punto", "Doblo", "Fiorino", "Tipo", "500", "Panda", "Ducato", "Albea"],
  Ford: ["Focus", "Fiesta", "Mondeo", "Kuga", "Puma", "Courier", "Connect", "Transit", "Transit Custom", "Ranger"],
  Volkswagen: ["Golf", "Polo", "Passat", "Jetta", "Tiguan", "Touran", "Caddy", "Transporter", "Crafter", "T-Roc"],
  Opel: ["Astra", "Corsa", "Insignia", "Mokka", "Vectra", "Combo", "Vivaro", "Zafira", "Meriva", "Grandland"],
  Peugeot: ["208", "301", "308", "3008", "2008", "5008", "Partner", "Boxer", "Expert", "406"],
  Citroën: ["C-Elysée", "C3", "C4", "C4 Cactus", "Berlingo", "Jumpy", "Jumper", "C5", "C3 Aircross", "Xsara"],
  Hyundai: ["i10", "i20", "i30", "Accent", "Elantra", "Tucson", "Santa Fe", "Kona", "Bayon", "Getz"],
  Kia: ["Picanto", "Rio", "Ceed", "Cerato", "Sportage", "Sorento", "Stonic", "Niro", "Carens", "Soul"],
  "Mercedes-Benz": ["A Serisi", "B Serisi", "C Serisi", "E Serisi", "S Serisi", "CLA", "GLA", "GLC", "Vito", "Sprinter"],
  BMW: ["1 Serisi", "2 Serisi", "3 Serisi", "4 Serisi", "5 Serisi", "X1", "X3", "X5", "116i", "320i"],
  Audi: ["A1", "A3", "A4", "A5", "A6", "Q2", "Q3", "Q5", "Q7", "TT"],
  Skoda: ["Fabia", "Octavia", "Superb", "Rapid", "Kamiq", "Karoq", "Kodiaq", "Yeti", "Roomster", "Scala"],
  Seat: ["Ibiza", "Leon", "Toledo", "Ateca", "Arona", "Alhambra", "Cordoba", "Altea", "Tarraco", "Exeo"],
  Dacia: ["Duster", "Sandero", "Logan", "Lodgy", "Dokker", "Spring", "Jogger", "Sandero Stepway"],
  Honda: ["Civic", "Accord", "CR-V", "HR-V", "Jazz", "City", "Insight"],
  Nissan: ["Micra", "Note", "Qashqai", "X-Trail", "Juke", "Navara", "NV200", "Almera", "Primera"],
  Mazda: ["Mazda2", "Mazda3", "Mazda6", "CX-3", "CX-5", "CX-30", "BT-50"],
  Mitsubishi: ["Lancer", "Colt", "ASX", "Outlander", "Space Star", "L200", "Pajero", "Eclipse Cross", "Carisma"],
  Suzuki: ["Swift", "Vitara", "S-Cross", "Baleno", "Jimny", "Celerio", "Ignis"],
  Chevrolet: ["Aveo", "Cruze", "Lacetti", "Captiva", "Spark", "Orlando", "Epica"],
  Volvo: ["S40", "S60", "S80", "V40", "V60", "XC40", "XC60", "XC90", "FH", "FM"],
  "Land Rover": ["Defender", "Discovery", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Freelander"],
  Jeep: ["Renegade", "Compass", "Cherokee", "Grand Cherokee", "Wrangler"],
  Isuzu: ["D-Max", "NPR", "NQR", "Trooper"],
  Iveco: ["Daily", "Eurocargo", "Stralis", "Trakker"],
  MAN: ["TGX", "TGS", "TGL", "TGM"],
  Scania: ["R Serisi", "P Serisi", "G Serisi", "S Serisi"],
  DAF: ["XF", "CF", "LF"],
  Tofaş: ["Şahin", "Doğan", "Kartal", "Linea", "Doblo"],
  Diğer: [],
};

export function modelleriGetir(marka: string): string[] {
  return MARKA_MODELLERI[marka] ?? [];
}
